### ISSUE TITLE
Missing Image

### ISSUE THREAD

**Issue by irms** [EditLLC/client-minderplus#1]
I was just about to use this site as an example to someone and noticed the image is missing.

<img width="704" alt="screenshot 2015-12-03 09 03 24" src="https://cloud.githubusercontent.com/assets/643997/11567643/cb32d5a0-999c-11e5-8e7e-794993e1a275.png">

Just letting you know. Not sure if the site was done or ..?

**Comment by rodneystrong** [comment]
I even had a commit specifically for that missing image.. and it goes missing again: c4afe092611002df415a9e8976fc43bb4810db78

**Comment by rodneystrong** [comment]
You're gonna love the commit message for this one... 3e0a994ed5d2875c60991274355323062174f3af
